spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: user de tu bd
    password: password de tu bd
    driverClassName: oracle.jdbc.driver.OracleDriver

  jpa:
    show-sql:true
    open-in-view:false
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
